spring:
  application:
    name: YOUR-NAME

  profiles:
    active: YOUR-PROFIL

  datasource:
    url: jdbc:mysql://localhost:3306/YOUR-NAME
    username:
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27017/YOUR-NAME

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: YOUR-KEY
  expiration: YOUR-EXPIRATION

baseUrl: YOUR-BASE
