spring:
  application:
    name: eni-store

  profiles:
    active: mongo

  datasource:
    url: jdbc:mysql://localhost:3306/eni-store
    username: root
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eni-store

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: 9f8c2b7e5a1d4c6f8e3b9a2c7d5f1e6a9b8c7d6e5f4a3b2c1d9e8f7a6b5c4d3
  expiration: 86400000

baseUrl: http://localhost:4200
